- 황창섭/chapter02/Chapter 2. 코틀린 기초.md
- 2장은 자바와 비슷하다고 느껴지는 부분이 많아 쉽게 쉽게 읽혔습니다. 코드 예제도 많아서 좋았습니다~
- var, val 구분 키워드가 상당히 매력적으로 느껴졌습니다. 자바에서는 항상 final을 붙이다 보니 코드가 길어지는 경향이 있었는데 간단하게 구분지을 수 있어서 좋았습니다.
- 저는 코틀린을 제대로 처음 접해봤는데 현재까지는 자바로 길게 풀어쓰는 코드들을 최대한 축약해서 만드는 느낌입니다. 코드를 짧고 간단히 짜는 것도 좋지만, 과도한 생략과 축약이 들어가면 가독성이 떨어질 수도 있지 않을까 생각됐습니다. 물론 눈에 익숙해지면 짧고 간단히 코드를 짤 수 있을 것 같아요.
> docs : 2장 황창섭 정리글 업로드

- 이기섭/practice/kotlin-lotto-study/part2- 코틀린 기초
#읽고 느낀점
아직은 익숙하지 않아 낯설지만 참 세련된 것 같네요.
val, var 요 발바들도 스터디하면서 사용해보니 익숙해지긴 하는데 , 여기저기 선언하다보니 비슷하게생겨서 헷갈리기도하고.. final이 그립기도 하고..
그래도 스마트캐스트는 편한 것 같습니다. 자바에서는 타입검사 해놓고도 다시 캐스팅해서 접근해야 해서 코드도 길어지고 지저분해지는 느낌이었는데 깔끔하게 표현되어서 좋은 것 같습니다.
다중 루프에서 레이블 지정(@)하는 것도 신선했습니다.
다른 분들은 어떤부분이 좋다고 생각드셨는지 궁금하네요!
> docs: 2장 이기섭 정리글 업로드

- 이상호/chapter3/3장 함수 정의와 호출.md
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter03/sub01/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter03/sub02/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter03/sub03/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter03/sub04/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter03/sub05/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter03/sub05/User.kt
- 코틀린은 자바 클래스를 확장해서 더 풍분한 기능 제공
- 함수 파라미터의 기본값을 정의, 이름붙인 인자 사용
- 최상위 함수와 프로퍼티 선언
- 모든 클래스의 API를 바꿀 필요없이 확장 가능
- 중위 호출을 통한 메서드나 확장 함수를 더 깔끔한 구문으로 호출
- 문자열 처리 시 다양한 문자열 처리 함수 제공
- 로컬 함수를 사용해서 중복 제공 및 코드를 깔끔하게 유지
해당 장에서도 코틀린만의 코드를 간결하게 사용하는 부분에 대해서는 좋았습니다.
단, 몇가지 규칙을 정하면 좋겠다 싶은 부분도 있어서요.
- 함수 파라미터 기본값 정의 부분은 많은 사람들이 사용하는 소스에서는 좀 더 명확하고 직관적인게 좋아서, 정적 팩토리를 통해서 어떤 의도로 사용하였는지 보여주는 것이 좋다고 생각해요.
- 이름붙인 인자도 신선하다고 느꼈지만, 이 방법보다는 좀 더 직관적으로 보여줄 수 있는 방법들은 많다고 생각해요. 무엇보다 라인이 길어질것 같아요.
- 확장 함수도 해당 기능이 강력하다고 생각이 되어요. 사실 util 을 별로 안 좋아해요.(우리 모두 core에게 당한적 있지 않나요?) 가능하면 로컬 함수를 사용하는게 좋다고 생각해요.
확장 함수 사용보다는 로컬 함수를 쓰는 것이 좀 더 캡슐화를 지키고, 나도 모르게 광범위하게 사용되다보면 문제가 생겼을 시 영향도도 클것 같아요.
어떻게 생각하시나요?
> docs: 3장 이상호 정리글 업로드

- 이기섭/practice/kotlin-lotto-study/part3 - 함수 정의와 호출.md
###읽고 느낀점
이름붙인 인자, 디폴트 파라미터 를 이용해 오버로딩을 최소화하고 코드의 가독성을 높일 수 있어보여 괜찮아 보였습니다.
특히 이번 챕터에서 확장함수를 보며 자바를 해치지 않고 코틀린스러움을 유지하며 자바와의 완벽한 호환을 가져가기 위한 중요한 역할을 했다는 생각이 들었습니다. 
###의문, 고민, 같이 이야기하고 싶은 부분
오버로딩이 많이 줄어들어 좋은점도 있겠지만, 반대로 하나의 함수의 역할이 비대해지게 될 수도 있을 것 같은 걱정이 들었습니다.
메서드의 책임을 적절하게 나눠야 할 것 같습니다.
> docs: 3장 이기섭의 정리글 업로드

- 한백규/03장 함수 정의와 호출/readme.md
java로 개발하면서 java collection stdlib 에서 지원하지 않는 기능을 쓰고 싶을 때 아쉬움이 있었는데요,
확장 함수로 커스텀할 수 있어 좋았습니다
그리고 java에선 `List<?>` 를 잘 사용하지 않고 일급 컬렉션으로 만들고 해당 클래스에서 비즈니스를 구현하는 일이 잦았는데요,
해당 변환 로직도 줄일 수 있을 것 같았습니다
메서드 호출 시 parameter에 이름을 붙일 수 있는 점과 순서를 바꿀 수 있는 점이 좋았습니다
java에선 parameter 순서는 헷갈릴 때가 많아 정의 부분과 호출 부분을 번갈아면서 봐야 해서 어지러웠습니다.
_(물론 ide가 hint로 도움을 주긴 하지만요,,,)_
코틀린의 디폴트 컬렉션 객체를 read only로 만들어준다는 점이 신기했습니다
코틀린 컨셉이 불변 객체 생성을 지향하는 걸 다시금 느꼈습니다
근데 사실 개발하면서 사용하고 있는 객체가 불변이 아닌걸 의식해서 개발에 불편함을 느낀적은 없습니다..?
entity validation 로직도 entity 내에 들어가야 하는게 맞지 않나..? 했습니다
맨 마지막 User 예제에서는 validation 부분을 확장 함수로 빼는 이유가 User를 간결하게 유지 해야 한다는 점이라 해서요.
확장 함수라 하더라도 User.kt 클래스 파일 내에 정의하거나, 유틸 클래스와 같은 ValidationUtil.kt 파일 내에 정의되어야 한다고 생각이 들었습니다.
> docs : 3장 한백규 정리글 업로드

- 황창섭/chapter03/Chapter 3. 함수 정의와 호출.md
- 확장 함수가 실무에서 많이 사용되는지는 모르겠지만 굉장히 강력해보이는 기능입니다. 특히 수신 객체 타입의 소스코드를 소유하지 않았어도, 수신 객체 타입이 코틀린으로 쓰이지 않았더라도, 수신 객체 타입이 final로 상속 할 수 없게 선언되었더라도 확장 가능하다는 점이 신기했습니다.
- 단순히 생각하면 첫 번째 파라미터가 수신 객체인 static 메소드이지만 일종의 눈속임으로 본래 수신 객체가 소유한 메서드처럼 보이는 점이 코드의 양을 엄청 줄이는 한편 까딱 잘못하면 커뮤니케이션 오류가 바로 발생할 수 있을 것 같았습니다.
- IDE 도움없이 호출하는 쪽에서 메서드와 확장 함수를 구분하기 어려울 것 같은데 이로 인해 개발자 간 커뮤니케이션 에러가 발생할 수 있을 것 같습니다.
> docs : 3장 황창섭 정리글 업로드

- 백운성/02_chapter03.md
- 확장함수를 사용해서 유틸성 메소드를 쉽게 만들 수 있음
- 클래스 없이 프로퍼티 및 함수 생성 가능
- 파라미터명을 사용해 순서에 상관없이 함수 호출 가능
- 디폴트 파라미터 함수를 통해 오버로딩 함수 추가 정의 필요성이 줄어듬
- 로컬 함수를 통해 깔끔한 리팩토링 가능
- 확장함수가 인상적이기 했음
- 이름붙인 인자 같은 경우 간략하게 name을 적어야해서 오히려 더 늘어남
- `""" """`를 이용해서 이스케이프를 회피할수 있는건 괜찮았음
- 대부분의 내용이 줄이거나 간략하게 사용할 수 있게 도와주는건데 요즘과 같은 좋은 IDE 사용 시대에 코드 한줄 덜 작성한다는게 큰 장점일까??
- final로 상속을 할 수 없게 선언된 경우에도 문제가 되지 않는데 java에서 final class의 경우 보안이나 설계 안정성이 중요한 경우 사용되는데 이걸 확장함수로 사용할 수 있으면 문제 있는거 아닌가?
> docs: 2주 3장 백운성 정리글 업로드

- 김병환/4장-클래스, 객체, 인터페이스.md
- 데이터 클래스 부분을 Lombok을 생각하며 재밌게 읽었습니다!
- Equals와 HashCode 부분을 보며, 예전에 읽었던 이펙티브 자바가 떠올라 복습하는 느낌이 들었습니다!
- 이번 장에서도 마찬가지로 코틀린이 굉장히 편리하다는 것을 느꼈습니다. java의 final 키워드가 가진 속성을 명시하지 않아도 되는 점이 매력적으로 느껴졌습니다!
- 평소에도 불변객체 생성과 접근 제어자 관리에 신경을 많이 쓰는 편인데 module 내에서 참조가 가능한 internal 제어자가 너무 좋아보였습니다! 평소 java로 개발을 할 때 4가지 접근제어자로 충분하다고 생각을 했었는데 internal이 있으면 유지보수성이 용이해질 것 같다고 생각이 드는데요. 어떻게 생각하시나요?
> docs : 4장 김병환 정리글 업로드

- 황창섭/chapter04/Chapter 4. 클래스, 객체, 인터페이스.md
- 새로운 언어를 배운다는 재미도 있지만 기존에 알고있던 자바 지식에 대한 점검과 헷갈렸던 부분에 대해 다시 한 번 공부할 기회가 되어 좋았습니다. 특히 코틀린은 익명 함수에서 final이 아닌 지역 변수를 사용할 수 있다는 내용이 있었는데 자바와의 차이를 보면서 되돌아볼 수 있는 기회가 되었습니다.
- 동반 객체와 최상위 함수는 static을 대체한다는 점에서 비슷한 것 같았습니다. 저는 캡슐화가 필요한가를 사용 판단 기준으로 잡으면 좋을 것 같다 생각했는데 다른 분들은 어떻게 생각하시나요?
> docs : 4장 황창섭 정리글 업로드

- 백운성/02_chapter04.md
- 클래스는 기본 `final`  
- 상속, 오버라이드는 `open` 필요  
- 인터페이스는 기본 메서드 가능, 중복 시 `override` 필수  
- `sealed`는 제한된 계층 표현 + `when` 분기 누락 방지  
- `data class`는 주요 메서드 자동 생성  
- `object`는 싱글턴, `companion object`는 정적 멤버용  
- `value class`는 값 하나 감싸는 경량 타입  
---
- `sealed` 덕분에 타입 안정성과 분기 누락 방지가 가능해 보여 좋았음  
- 클래스 키워드(`open`, `final`)를 명시하는 방식도 코드의 의도를 드러내서 긍정적임  
- 다만 비슷한 문법들이 다양하게 흩어져 있어 헷갈릴 수 있음  
- Java와 구조가 겹치는 부분이 생각보다 많음
---
- 전체적으로 Kotlin 문법이 깔끔하다는 느낌은 있으나, val/var를 무조건 변수 선언 시 함께 써야 하는 구조라 더 헷갈림 (아직은 익숙하지 않아서 그럴까???)
- 문법은 깔끔한데, 이걸 언제 어디에 어떻게 쓰면 좋을지 프로젝트등을 통해 감이 필요한 상황임  
- 그리고 책의 해설이 메서드, 함수, 기준 클래스 왔다 갔다해서 오히려 더 헷갈림... @_@
> docs : 4장 백운성 정리글 업로드

- 한백규/04장 클래스, 객체, 인터페이스/readme.md
기본적으로 final로 선언되고 커스텀하게 로직을 구현하고 싶으면 open을 지정해주어야 한다는점이 신기했습니다.
이 또한 불변 지향 언어 특성이라고 생각이 들었네요.
근데 사실 대부분 코프링에선 gradle에서 all open으로 entity를 선언하는데요,
코틀린 지향점을 잘 따라서 코프링 진영 컨벤션이 구성된건지는 의문이었습니다.
참고 자료)
- [Kotlin JPA 필수 지식](https://hyeon9mak.github.io/kotlin-jpa-essentials/)
companion object, sealed, anonymous 등 다양한 코틀린 키워드를 배웠습니다.
이 중 코프링에 실제 적용될만한게 어떤게 있을지 궁금했습니다 🤔
> docs: 4장 한백규 정리글 업로드

- 이상호/chapter4/4장 클래스, 객체, 인터페이스.md
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub01/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub01/Button.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub01/Button2.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub01/Clickable.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub01/Focusable.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub01/State.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub01/TalkativeButton.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub01/View2.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub02/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub02/LengthCounter.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub02/User.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub02/User2.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub02/User3.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub02/User4.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub02/User5.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub03/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub03/Customer.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub04/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub04/MyClass.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub04/Payroll.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub04/Person.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub05/Application.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub05/UsdCent.kt
- 이상호/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/chapter04/sub05/UsdCent2.kt
- 인터페이스는 자바와 비슷
- 오버라이드 사용 시 필수로 `override` 수정자 사용
- 구현을 작성한 후 메서드를 추가한 경우 실수로 메서드를 재정의하는 실수를 방지
- 기본적으로 모든 클래스와 메서드는 최종 클래스, 필요 시 `open` 수정자 사용하여 서브클래스, 재정의 등 사용
- 추상 클래스에는 일반적으로 구현이 없고 서브클래스에 재정의해야 하는 추상 멤버 포함, `open` 필요 없음
- 클래스 초기화 시 `init` 활용하여 검증, 초기값 등 활용
- `object` 싱글턴 객체 만들기
- `companion` 정적 팩토리 메소드 및 글로벌 또는 지역 상수
- `@JvmInline` 객체의 불필요한 인스턴스화를 방지
눈에 잘 들어오는 내용과 아직까지 눈에 잘 들어오지 않는 내용들로 구분이 되는 장이었습니다.
자바에서 생성자 또는 정적 팩토리 메소드에서 생성자 초기화 단계에서 검증용 메소드를 만들게 되는데, init을 잘 활용할 수 있을것 같습니다.
해당 장에서 저희 로또 프로그램 구현을 위한 내용들이 많이 나온거 같습니다. 
이제 슬슬 코틀린으로 로또 구하는 부분을 시작해 보시죠!
> docs: 4장 이상호 정리글 업로드

- 김병환/5장-람다를 사용한 프로그래밍.md
- 코틀린 람다의 with, apply, also 함수가 재미있게 느껴졌습니다!
- buildString, buildList, buildSet, buildMap 함수가 코드를 작성할 때 이쁘고 우아하게 만들 수 있을 것 같아 탐이 났습니다. 
- it은 자바에서 함수형 연산에서 x를 쓰는 것과 비슷하다고 느꼈는데요. 이름을 지정하지 않아도 되는 것이 장점이지만 반대로 지정하지 않는 것이 단점이 될 수도 있을 것 같습니다. 명시적인 선언은 유지보수성을 높여준다고 생각해요! 다들 어떻게 생각하시나요?
> docs : 5장 김병환 정리글 업로드

- 한백규/05장 람다를 사용한 프로그래밍/readme.md
let, with, also, apply, run 등 코틀린 스코프 함수를 얼른 비즈니스에 적용해보고 싶단 생각이 들었습니다.
정의와 예제만으로는 확 와닿지가 않아서요,,
체이닝으로 행위를 표현할 수 있다는 점이 매력적입니다.
코틀린에서의 람다와 무관하게 비즈니스 개발 시에도 람다로 개발하는 점을 선호하시는지 궁금합니다
과도한 축약은 오히려 가독성을 낮춘다 생각이 들때도 종종 있었습니다..!
> docs: 5장 한백규 정리글 업로드

- 백인준/Part5- 람다를 사용한 프로그래밍.md
📚 읽고 느낀 점
자바와 거의 비슷하게 나온 느낌입니다. 
🤔 의문, 고민, 같이 이야기하고 싶은 부분
람다 개발을 때에 따라 선호하는 편인데요.
여러분은 어떨때 사용하시나요?
> docs : 5장 백인준 정리글 업로드

- 황창섭/chapter05/Chapter 5. 람다를 사용한 프로그래밍.md
- 코틀린의 함수형 스타일이 강력하고, 자바와의 상호 운용성이 뛰어남을 알 수 있었습니다.
- 외부 변수를 캡처하면 성능 문제가 발생할 것 같아요. 자바에서도 AtomicReference나 배열등의 눈속임으로 final이 아닌 변수를 람다식 내에서 사용할 수는 있지만 지양해야할 부분이라 생각합니다.
> docs : 5장 황창섭 정리글 업로드

- 김병환/6장-컬렉션과 시퀀스.md
- 모던 자바의 Stream을 복습하는 느낌이 들었습니다!
- lazy loading에 관한 유용함이 잘 드러난 챕터였던 것 같습니다. Kotlin의 sequence 뿐만 아니라 여러 java library에서도 lazy loading 개념을 접목한 기능이 많은데요. 상황에 따라서 잘 쓰기가 생각보다 힘든 것 같습니다. 사용하는 함수의 javadoc을 읽는 것을 습관화하면 좋을 것 같아요!
> docs : 6장 김병환 정리글 업로드

- 한백규/06장 컬렉션과 시퀀스/readme.md
자바의 stream과 거의 유사하여 코틀린 전환 시에 비교적 수월하게 느껴질 것 같습니다.
stream()과 같은 체이닝 메서드가 없어져 이 점도 좋게 느껴졌습니다.
어떤 기준을 토대로 자료구조를 선택해야할 지 고민이 들었습니다
단순하게 데이터 양의 차이로 지연 계산으로 성능 이점을 가져가야 할때만은 아닐 것 같아서요..!
> docs: 6장 한백규 정리글 업로드

- 황창섭/chapter06/Chapter 06. 컬렉션과 시퀀스.md
자바와의 차이가 없는 것 같았습니다.
- 왜 Stream을 이용하지 않고 코틀린에서는 Sequence라는 것을 이용했는지가 궁금하여 검색해보았습니다. 크게 두 가지 사유로 보였는데 1. JVM 종속적이지 않고 멀티플랫폼 지원을 위해라는 이유가 있었고 2. 기본적으로 parallelStream 이라던가 복잡한 기능은 모두 제거하고(병렬처리는 코루틴으로 유도) 지연 처리 기능에만 집중해서 만들었다고 하네요.
> docs : 6장 황창섭 정리글 업로드

- 백운성/05_chapter06.md
- 백운성/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/Chapter02.kt
- 백운성/practice/kotlin-lotto-study/src/main/kotlin/io/study/kotlin/Chapter06.kt
- Java stream API와 거의 비슷한 대부분의 API를 지원하며 사용방법도 비슷함
- filter, map, reduce, fold, partition, groupBy, associate, associateWith, associateBy, all, any, none, count, find, zip, flatMap, flatten
---
- 전반적으로 이번장은 java와 매우 흡사했으며, 유틸 같은 특수한 API가 몇개 더 추가 된 된 같음, 필요할 떄 사용하면 편할 것 같음
- partition, associate, associateWith, associateBy
- 처음에 steam을 사용하지 않아 더 간단한가 했는데 `asSequence`를 사용해야 java처럼 동작하여 비슷한 것 같음
---
- 위에서 말한 유틸성의 API가 많이 있긴하지만 그게 장점일지는 생각해봐야겠당
- Java에서는 `reduce`가 다양한 파라미터로 존재하는데 여기서는 `fold`라는 메소드가 별도로 존재한다는게 오히려 많은 것들을 외워야하나 싶다.
- 오히려 깔끔한 기능을 작게 제공하고 그걸 잘 조합해서 사용하는 것이 더 좋을때가 있을 것 같다.
---
> docs : 6장 백운성 정리글 업로드

- 이기섭/practice/kotlin-lotto-study/part6 - 컬렉션과 시퀀스
java와 매우 비슷하게 느꼈고 더 명료하고 다양한 함수를 제공해준다고 생각되었습니다. 
자바에서 컬렉션과 스트림의 함수들을 한정적으로만 사용해서 그런지 색다르게 느껴지던게 있었고, windowed ,associate 가 유용한 데가 있을 것 같았습니다.
다들 미션 진행하셨을까요? 저는 차주에 꼭 진행해보려 하는데 조금이나마 코틀린 스러운 코드로 할 수 있을지 걱정되네요 ㅎㅎ
> docs : 6장 이기섭 정리글 업로드

- 김병환/7장-널이 될 수 있는 값.md
- 널 처리를 컴파일 시점에 알 수 있는 것이 가장 큰 장점으로 느껴졌습니다.
- 평소에 java 개발을 할 때 NotNull, Nullable annotation을 명시적으로 쓰려고 하지는 않았는데 만약 코틀린으로 해당 코드를 참조하면 불편할 수 있겠다는 생각이 들었습니다. 중요한 메소드는 붙이는 습관을 들이는 게 좋을 것 같네요!
> docs : 7장 김병환 정리글 업로드

- 백운성/06_chapter07.md
| expression | description  |
|------------|--------------|
| `?`        | null 허용 변수 선언 |
| `?.`       | null-safe 호출 |
| `?:`       | null이면 기본값   |
| `!!`       | null 아님을 보장 |
| `let`      | null이 아닐 때 블록 실행 |
---
- 자바에서 null 처리라는게 개발하다보면 일단 null이 들어오지 않는다고 기본으로 생각하고 꼭 필요한 부분에 예외처리 하는게 일반적인데 not-null과 nullable을 구분해서 모든 케이스를 개발하는게 더 빡신것 같다. 
- 반드시 null이 들어오면 안된다면 예외처리를 명확하게 하거나 annotation을 붙이는게 자바를 사용하는 입장에서 좀더 명확해 보인다.
---
- 책 번역이 좀 이상한 부분들이 있어 간단한 내용인데도 이해하는데 시간이 소요되었음
- 코틀린을 알아가면서 점점 꼭 필요한 기능들일까? 라는 의문이 들긴함 
---
> docs : 7장 백운성 정리글 업로드

- 이기섭/practice/kotlin-lotto-study/part7 - 널이 될 수 있는 값
소문 무성했던 코틀린의 널처리를 알게되어 의미있는 장이었던 것 같습니다.
타입에 널관련 처리를 명시하여 컴파일 단계에서 오류를 사전에 방지할 수 있어 안정적으로 느껴졌습니다. 
let 도 굉장히 유용해보였는데, Optional 의 map 과 비슷해보였지만 더 간결하고 유용해보였습니다.
- Optional 을 반환타입으로만 사용하고 있지 않았어서 반성의 시간이 또 찾아왔었네요..
> docs : 7장 이기섭정리글 업로드

- 한백규/07장 널이 될 수 있는 값/readme.md
코틀린에서 다양한 방식으로 Null safety를 보장해주는 점이 좋았습니다.
그 중에서 `company?.address?.name` 과 같은 방식으로 체이닝을 계속 걸면 아무 생각 없이 개발은 쉽게 하면서도 
다른 사람이 보기엔 어지러울 것 같다 생각이 들었습니다
제공해주는 기능이 많다 보니 각자 개발하면서 null checking을 달리 가져갈 것 같다 생각이 들었습니다.
하나의 서비스를 여러명이 개발한다면 convention을 맞추는것도 좋다 생각이 들었는데, 비즈니스가 다르다 보니 가능할지 의문이었습니다.
이에 대한 생각이 궁금합니다
> docs: 7장 한백규 정리글 업로드

- 김병환/8장-기본 타입, 컬렉션, 배열.md
- java와 코틀린을 혼합해서 쓴다면 컬렉션에 유의해야할 것 같네요!
- 읽기 전용이 불변은 아니다 라는 사실이 꽤나 재밌게 느껴졌습니다. 사실 개발을 하다보면 종종 접하는 경우인데요. 어떻게 보면 매번 복사해서 사용하게 하면 성능이 떨어지니 나름의 trade-off인 것 같습니다! 다들 어떻게 생각하시나요?
> docs : 8장 김병환 정리글 업로드

- 황창섭/chapter08/Chapter 08. 기본 타입, 컬렉션, 배열.md
- 코틀린 기본 타입: Byte, Short, Int, Long, Float, Double, Char, Boolean
- Any: 모든 널이 될 수 없는 코틀린 타입의 최상위 조상 타입
- Unit: 함수가 반환할 값이 없음을 나타내며, 자바의 void와 유사하지만 객체
- Nothing: 절대 값을 반환하지 않거나 실행이 정상적으로 끝나지 않음을 나타내는 타입
자바의 단점(자동 형변환, 컬렉션 변경 가능성 모호 등)을 개선하려는 코틀린의 설계 노력이 잘 보였습니다.
> docs : 8장 황창섭 정리글 업로드

- 김병환/9장-연산자 오버로딩과 다른 관례.md
- 관례가 흥미로웠습니다. 실제 비즈니스 로직이 가독성이 좋아질 것 같아요.
- 구조 분해 선언이 개인적으로 탐이 났습니다. 실제로 개발을 진행할 때 꽤나 자주 쓸 수 있고, 코드 가독성도 좋아질 것 같아요. 여러분들은 관례, 구조 분해 선언, 위임 키워드 등 이번 장에서 배운 것들 중 어떤 것이 흥미로우셨나요?
> docs : 9장 김병환 정리글 업로드

- 황창섭/chapter09/Chapter 09. 연산자 오버로딩과 다른 관례.md
특정 연산자나 구문이 내부적으로 어떤 메서드 호출로 변환되는지 나와있어 좋았습니다
구조 분해 선언의 위치 기반 한계가 굉장히 크게 다가왔습니다. 프로퍼티 선언 순서 변경만으로 깨질 수 있는 코드가 생성된다는 점에서 정말 변경되지 않을 data class에서만 사용해야 한다고 느껴졌습니다.
> docs : 9장 황창섭 정리글 업로드

- 한백규/08장 기본 타입, 컬렉션, 배열/readme.md
- 한백규/09장 연산자 오버로딩과 다른 관레/readme.md
값 계산 시에 java 에선 BigDecimal 필드를 꺼내서 multiply, divide, ... 체이닝으로 구현 해야 하는 점이 불편했습니다.
연산자 오버로딩으로 깔끔하게 구현할 수 있을것 같단 생각이 들었습니다.
`by lazy` 키워드에 해당하는 부분을 읽으면서 jpa lazy loading 개념이 떠올랐습니다
해당 키워드로 spring business 에서 어떤 상황에 구현하게 될지 궁금했습니다..!
> docs: 9장 한백규 정리글 업로드

- 김병환/10장-고차함수-람다를 파라미터와 반환값으로 사용.md
- 람다에 대해 복습할 수 있는 좋은 챕터였습니다!
- 인라이닝이 꽤 흥미로웠습니다. 가끔 컴파일된 이후, 바이트코드를 쭉 볼 때가 있는데 내가 짠 부분에서 비효율적인 부분은 없는지 검토해봐도 좋을 것 같아요!
> docs : 10장 김병환 정리글 업로드

- 강희정/note/chapter10.md
- 람다에 대해서 이해도가 그닥 높지 않았는데, 잘 설명해줘서 이번 기회에 짚고 넘어갈 수 있던 것 같습니다.
- 인라이닝 기능이 흥미로웠습니다. 모든 기술이 그렇듯, 어떤 상황에서 모든 것을 해결해 주는 silver bullet은 없는 것 같아요 😅 inline도 장단점이 확실하더라구요..
inline, noinline에 대해서 찾아보다가 책에서는 다루지 않고 있던 crossline이라는 변경자가 있어서 함께 공유하면 좋을 것 같아서 간단히 가져왔습니다 🙇‍♀️ 
(by 구글 검색 결과 및 GPT)
키워드 | 의미 | 언제 사용하나?
-- | -- | --
noinline | 람다를 인라인하지 말고 일반 함수처럼 호출하도록 컴파일하라 | 인라인 함수 안에서 람다를 나중에 호출하거나 저장해야 할 때
crossinline | 인라인은 하지만 return으로 바깥 함수를 빠져나가지 못하게 제한 | 인라인 람다 안에서 non-local return을 허용하면 안 되는 상황
-> 람다 함수는 기본적으로 비로컬 return인데, 람다 안에서 비로컬 return을 허용하면 안 되는 상황이란 것이 무엇일까?
```kotlin
inline fun foo(block: () -> Unit) {
val r = Runnable {
block()  // 컴파일 오류
}
r.run()
}
```
- block()은 인라인이지만,
- Runnable의 실행 컨텍스트는 foo()의 스택 밖
- block() 안에서 return 하면, foo()를 벗어나게 되므로 스택이 깨짐
-> 이걸 컴파일 타임에 막기 위해 crossinline 필요 …
> docs: 10장 강희정 정리글 업로드

- 백운성/10_chapter10.md
- 고차 함수  
- 함수를 인자로 받거나 반환  
- 람다로 중복 제거 및 추상화 가능
- inline 함수  
- 람다 성능 최적화 (람다 객체 생략)  
- return 등 흐름 제어 가능 (non-local return)
- 자원 관리 고차 함수  
- `withLock`: 락 자동 해제  
- `use`: 자원 자동 닫기  
- `useLines`: 파일 라인 처리 + 자동 해제
- 람다에서의 return  
- 일반 return → 바깥 함수까지 종료  
- `return@label`, 익명 함수 → 로컬 반환
- 익명 함수 return → 항상 람다 내부 로직에서만 리턴됨
---
---
> docs : 10장 백운성 정리글 업로드

- 이상호/chapter10/10장 고차 함수: 람다를 파라미터와 반환값으로 사용.md
| 항목 | 고차 함수 | 인라인 함수 |
| -- | -- | -- |
| 목적 | 함수를 인자로 받거나 반환하기 위해 사용 | 성능 향상을 위해 함수 코드를 삽입 키워드 | 없음 | inline |
| 장점 | 코드의 유연성과 재사용성 | 함수 호출 오버헤드 제거, 성능 개선 |
| 단점 | 런타임에 람다 객체 생성으로 비용 발생 | 코드 증가(바이트코드), 디버깅 어려움 |
이제 스터디도 중간 반환점을 돌고 있는거 같아요! 
아직 미션으 전이라면 서둘러 미션을 진행해보셔요!
> docs: 10장 고차 함수: 람다를 파라미터와 반환값으로 사용

- 황창섭/chapter10/Chapter 10. 고차 함수.md
람다 사용 시 발생할 수 있는 부가 비용을 인라인 함수를 통해 해결할 수 있다는 점이 흥미로웠습니다. 
`operation: (Int, Int) -> Int` 와 같이 함수 타입이 명시될 때, 파라미터가 많아지거나 함수 타입 자체가 복잡해지면 가독성이 떨어질 수 있을 것 같습니다. 가독성을 높일 수 있는 다른 좋은 방법이나 컨벤션이 있을까요?
> docs : 10장 황창섭 정리글 업로드

- 김병환/11장-제네릭스.md
- 코틀린에서 제네릭을 다루는 방법이 흥미로웠습니다!
- 무공변, 공변, 반공변 등까지 용어가 익숙하진 않았지만 재밌는 내용이었어요!
> docs : 11장 김병환 정리글 업로드

- 이기섭/practice/kotlin-lotto-study/part11 - 제네릭스.md
제네릭에대해 다양하게 공부해본 단원이었습니다. inline,reified 을 통해 실체화된 타입파라미터 활용과 제약사항이 신기하고 아직 이해가 다 되지는 않습니다. 공변성, 반공변성, 무공변성 등을 개념적으로 처음 알게되어 신기했습니다. 공부는 중요하군요.
이해도 잘 안되고 더 안읽히지만... 그래도 다시 화이팅입니다!
> docs: 11장 이기섭 정리글 업로드

- 전종혁/12.어노테이션과리플렉션.md
- 용어들이 너무 어렵게 나와서 이해하기가 힘들었다.
- 코틀린의 어노테이션과 리플렉션에은 자바와 비슷한 것 같습니다.
> docs: 12장 어노테이션과 리플렉션

- 이기섭/practice/kotlin-lotto-study/part12 - 어노테이션과 리플렉션.md
친숙한 Json 직렬화/역직렬화를 리플렉션과 어노테이션으로 어떻게 구현했는지 하나하나 되짚어봐서 좋았던 것 같습니다.
KFunction..KClass 등의 표현이 한국스러워서 친숙했습니다ㅋ
> docs: 12장 이기섭 정리글 업로드

- 이상호/chapter12/12장 어노테이션과 리플렉션.md
- 어노테이션 클래스를 기본 생성자가 있는 클래스로 선언하면 모든 매개변수가 본문 없이 val 프로퍼티로 표시
- 리플렉션 API를 사용하면 런타임에 객체의 메서드와 프로퍼티를 동적으로 열거하고 접근 가능
- KClass 인스턴스를 얻으려면 클래스에 ClassName::class를 사용하거나 객체 인스턴스에 대한 객체 이름::클래스를 사용
- KFunction과 KProperty 인터페이스는 모두 일반 호출 메서드를 제공하는 KCallable을 확장
- KCallable.callBy 메서드는 기본 매개변수 값으로 메서드를 호출하는 데 사용
- KFunction0, KFunction1 등은 호출 메서드를 사용하여 호출할 수 있는 매개변수 수가 다른 함수
- KProperty0과 KProperty1은 값을 검색하기 위한 get 메서드를 지원하는 수신자 수가 다른 프로퍼티
- KMutableProperty0과 KMutableProperty1은 이러한 인터페이스를 확장하여 set 메서드를 통해 프로퍼티값을 변경할 수 있도록 지원
- KType의 런타임 표현을 얻으려면 typeof<T>()를 사용
- 자바와 비슷하다는 느낌을 받았음
> docs : 12장 이상호 정리글 업로드

- 이상호/chapter13/13장 DSL 만들기.md
- Kotlin DSL에서는 수신 객체 지정 람다와 확장 함수를 활용해 읽기 쉬운 도메인 특화 언어를 구성
- buildString, apply, with 등의 함수는 DSL에서 블록 구조를 표현하는 데 유용
- HTML DSL은 태그 구조를 클래스와 함수로 구성하여 타입 안전한 방식으로 문서를 생성
- invoke 연산자를 사용하면 객체를 함수처럼 호출할 수 있어 DSL 문법을 자연스럽게
- 멤버 확장 함수는 기존 클래스에 새로운 문법을 추가할 수 있어 SQL DSL 같은 복잡한 구조에도 잘 활용
- DSL의 특징에 대해서 잘 이해할 수 있었던것 같고 QueryDSL의 대한 이해도 같이 올라갔음
- 끝까지 유종의미를 거두었으면 좋겠습니다~ 다들 화이팅!
> docs : 13장 이상호 정리글 업로드

- 김병환/14장-코루틴.md
- 늘 코루틴이 궁금했는데 이번 챕터로 완벽히 정리되는 느낌이었어요!
- 동시성과 병렬성 그리고 그것들의 문제점을 해결하는 과정을 보니 재밌었습니다!
> docs : 14장 김병환 정리글 업로드

- 김병환/15장-구조화된 동시성.md
- 코루틴 스코프에 대한 내용이 흥미로웠습니다!
- 취소방식들과 취소의 메커니즘이 편리하다고 느꼈어요.
- 마지막까지 화이팅입니다!
> docs : 15장 김병환 정리글 업로드

- 이기섭/practice/kotlin-lotto-study/part14 - 코루틴
- 이기섭/practice/kotlin-lotto-study/part15 - 구조화된 동시성
소문의 코루틴을 만나게되어 반가웠습니다.
실무에서 실제로 비즈니스를 구현하며 사용해봐야겠지만, 일시중단과 중단지점부터 재개가 가능하고, 계층을 통해 취소 전파가 가능한부분이 감명깊었습니다.
###의문, 고민, 같이 이야기하고 싶은 부분
늦어서 죄송합니다 ㅠㅠ 모두 고지가 얼마 남지 않았습니다! 화이팅하죠!
> docs : 14장,15장 이기섭 정리글 업로드 
